using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using TeklaMcp.Core.Models;

namespace TeklaMcp.Scripting;

/// <summary>
/// Search over the local Tekla Open API Markdown reference generated by
/// <c>tools/TeklaApiDoc</c> (one <c>Full.Type.Name.md</c> per type, member lines starting
/// with <c>- `</c>). Lets agents verify type/member signatures BEFORE writing a script,
/// instead of hallucinating them. The reference is git-ignored (Trimble content), so
/// everything degrades to a "how to generate it" hint when the folder is missing.
/// </summary>
public static class ApiReference
{
    /// <summary>Env var pointing at the generated reference folder (overrides probing).</summary>
    public const string DirEnvVar = "TEKLA_MCP_API_REF_DIR";

    private const string HowToGenerate =
        "The local API reference is not available. From a source checkout, generate Model + " +
        "Drawing docs with tools/TeklaApiDoc (see tools/TeklaApiDoc/README.md) into " +
        "reference/tekla-api. For a release install, generate/download that folder separately " +
        "and set " + DirEnvVar + " to it. Without it, tekla_check_csharp still reports compiler errors.";

    private const int MaxLinesPerType = 8;

    public static ApiReferenceStatus GetStatus()
    {
        var dir = FindDirectory();
        var result = new ApiReferenceStatus
        {
            Available = dir != null,
            Directory = dir ?? "",
        };
        if (dir == null)
        {
            result.Guidance = HowToGenerate;
            return result;
        }

        try
        {
            var names = Directory.EnumerateFiles(dir, "*.md")
                .Select(Path.GetFileNameWithoutExtension)
                .Where(name => !string.IsNullOrWhiteSpace(name) &&
                               !string.Equals(name, "INDEX", StringComparison.OrdinalIgnoreCase))
                .Select(name => name!)
                .ToList();
            result.TypeCount = names.Count;
            AddModule(result, names, "Tekla.Structures.Model.", "Model");
            AddModule(result, names, "Tekla.Structures.Drawing.", "Drawing");
            AddModule(result, names, "Tekla.Structures.Geometry3d.", "Geometry3d");
            if (!result.Modules.Contains("Model"))
                result.Warnings.Add("Model API pages are missing.");
            if (!result.Modules.Contains("Drawing"))
                result.Warnings.Add(
                    "Drawing API pages are missing; regenerate with Tekla.Structures.Drawing.dll.");
            result.Guidance = result.Warnings.Count == 0
                ? "Offline Tekla API reference is ready (Model + Drawing coverage detected)."
                : "Reference is usable but incomplete: " + string.Join(" ", result.Warnings);
        }
        catch (Exception ex)
        {
            result.Available = false;
            result.Warnings.Add("Reference directory could not be inspected: " + ex.Message);
            result.Guidance = HowToGenerate;
        }
        return result;
    }

    /// <summary>Locate the reference folder: env var first, then walking up from the app/current dir.</summary>
    public static string? FindDirectory()
    {
        var env = Environment.GetEnvironmentVariable(DirEnvVar);
        if (!string.IsNullOrWhiteSpace(env) && HasMarkdownFiles(env))
            return env;

        foreach (var start in new[] { AppContext.BaseDirectory, SafeCurrentDirectory() })
        {
            var dir = start;
            for (var i = 0; i < 8 && !string.IsNullOrEmpty(dir); i++)
            {
                var candidate = Path.Combine(dir, "reference", "tekla-api");
                if (HasMarkdownFiles(candidate))
                    return candidate;
                dir = Path.GetDirectoryName(dir);
            }
        }
        return null;
    }

    public static ApiSearchResult Search(string query, int limit = 10)
    {
        var result = new ApiSearchResult { Query = query ?? "" };

        var dir = FindDirectory();
        if (dir == null)
        {
            result.Guidance = HowToGenerate;
            return result;
        }

        result.ReferenceAvailable = true;
        result.ReferenceDir = dir;

        var tokens = Tokenize(query);
        if (tokens.Count == 0)
        {
            result.Guidance = "Query is empty — pass a type or member name fragment, e.g. 'Beam profile' or 'GetReportProperty'.";
            return result;
        }

        limit = Math.Min(Math.Max(limit, 1), 50);

        // Score every type file: strong signal when all tokens appear in the type name,
        // otherwise match member signature lines (all tokens on one line, case-insensitive).
        var hits = new List<(ApiSearchHit Hit, int Score)>();
        IEnumerable<string> searchFiles;
        try { searchFiles = Directory.EnumerateFiles(dir, "*.md").ToList(); }
        catch (Exception ex)
        {
            result.ReferenceAvailable = false;
            result.Guidance = "Reference directory could not be read: " + ex.Message + ". " + HowToGenerate;
            return result;
        }
        foreach (var file in searchFiles)
        {
            var typeName = Path.GetFileNameWithoutExtension(file);
            if (typeName.Equals("INDEX", StringComparison.OrdinalIgnoreCase))
                continue;

            var nameMatches = tokens.Count(t => typeName.IndexOf(t, StringComparison.OrdinalIgnoreCase) >= 0);
            List<string> lines;
            try
            {
                lines = MatchMemberLines(file, tokens);
            }
            catch
            {
                continue;
            }

            if (nameMatches < tokens.Count && lines.Count == 0)
                continue;

            var score = (nameMatches == tokens.Count ? 1000 - typeName.Length : 0) + lines.Count;
            hits.Add((new ApiSearchHit { Type = typeName, MatchingMembers = lines }, score));
        }

        foreach (var hit in hits.OrderByDescending(h => h.Score).Take(limit))
            result.Hits.Add(hit.Hit);
        result.TotalMatches = hits.Count;

        result.Guidance = result.Hits.Count == 0
            ? "No matches. Try fewer/shorter tokens (e.g. 'ReportProperty' instead of a full sentence), or a namespace fragment like 'Model.UI'."
            : "Use tekla_get_api_doc with a Type value to read the full signatures for that type.";
        return result;
    }

    public static ApiTypeDoc GetTypeDoc(string typeName, int maxChars = 24_000)
    {
        var result = new ApiTypeDoc { TypeName = typeName ?? "" };

        var dir = FindDirectory();
        if (dir == null)
        {
            result.Guidance = HowToGenerate;
            return result;
        }

        if (string.IsNullOrWhiteSpace(typeName))
        {
            result.Guidance = "Pass a type name, e.g. 'Beam' or 'Tekla.Structures.Model.Beam'.";
            return result;
        }

        List<string> files;
        try
        {
            files = Directory.EnumerateFiles(dir, "*.md")
                .Where(f => !Path.GetFileNameWithoutExtension(f).Equals(
                    "INDEX", StringComparison.OrdinalIgnoreCase))
                .ToList();
        }
        catch (Exception ex)
        {
            result.Guidance = "Reference directory could not be read: " + ex.Message + ". " + HowToGenerate;
            return result;
        }

        // Exact full name, then exact short name (suffix), then substring — all case-insensitive.
        var trimmed = typeName!.Trim();
        var file = files.FirstOrDefault(f =>
            Path.GetFileNameWithoutExtension(f).Equals(trimmed, StringComparison.OrdinalIgnoreCase));
        if (file == null)
        {
            var exactShortMatches = files.Where(f =>
                    Path.GetFileNameWithoutExtension(f).EndsWith(
                        "." + trimmed, StringComparison.OrdinalIgnoreCase))
                .ToList();
            if (exactShortMatches.Count > 1)
            {
                result.Suggestions = exactShortMatches
                    .Select(Path.GetFileNameWithoutExtension)
                    .Where(name => name != null)
                    .Select(name => name!)
                    .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
                    .Take(20)
                    .ToList();
                result.Guidance =
                    "Short type name is ambiguous. Pass one fully-qualified name from Suggestions.";
                return result;
            }
            file = exactShortMatches.SingleOrDefault();
        }

        if (file == null)
        {
            result.Suggestions = files
                .Select(Path.GetFileNameWithoutExtension)
                .Where(n => n!.IndexOf(trimmed, StringComparison.OrdinalIgnoreCase) >= 0)
                .OrderBy(n => n!.Length)
                .Take(10)
                .Select(n => n!)
                .ToList();
            result.Guidance = result.Suggestions.Count > 0
                ? "No exact type match — did you mean one of Suggestions?"
                : "No type matched. Use tekla_search_api to find the right type name first.";
            return result;
        }

        result.Found = true;
        result.TypeName = Path.GetFileNameWithoutExtension(file);
        string text;
        try { text = File.ReadAllText(file); }
        catch (Exception ex)
        {
            result.Found = false;
            result.Guidance = "The matched reference page could not be read: " + ex.Message;
            return result;
        }
        maxChars = Math.Min(Math.Max(maxChars, 1_000), 100_000);
        if (text.Length > maxChars)
        {
            text = text.Substring(0, maxChars) + "\n…(truncated — ask for a larger maxChars if needed)";
            result.Truncated = true;
        }
        result.Markdown = text;
        return result;
    }

    private static List<string> MatchMemberLines(string file, List<string> tokens)
    {
        var matches = new List<string>();
        foreach (var raw in File.ReadLines(file))
        {
            if (!raw.StartsWith("- ", StringComparison.Ordinal))
                continue;
            var line = raw;
            if (tokens.All(t => line.IndexOf(t, StringComparison.OrdinalIgnoreCase) >= 0))
            {
                matches.Add(line.Length > 300 ? line.Substring(0, 300) + "…" : line);
                if (matches.Count >= MaxLinesPerType)
                    break;
            }
        }
        return matches;
    }

    private static List<string> Tokenize(string? query)
        => (query ?? "")
            .Split(new[] { ' ', '\t', ',', ';', '(', ')', '.', '`', '\'', '"' }, StringSplitOptions.RemoveEmptyEntries)
            .Where(t => t.Length >= 2)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(6)
            .ToList();

    private static string SafeCurrentDirectory()
    {
        try { return Directory.GetCurrentDirectory(); }
        catch { return AppContext.BaseDirectory; }
    }

    private static bool HasMarkdownFiles(string? directory)
    {
        if (string.IsNullOrWhiteSpace(directory) || !Directory.Exists(directory)) return false;
        try { return Directory.EnumerateFiles(directory, "*.md").Any(); }
        catch { return false; }
    }

    private static void AddModule(
        ApiReferenceStatus result,
        IEnumerable<string> names,
        string prefix,
        string module)
    {
        if (names.Any(name => name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)))
            result.Modules.Add(module);
    }
}
