using System.Collections.Generic;
using System.ComponentModel;
using ModelContextProtocol.Server;
using TeklaMcp.Core;
using TeklaMcp.Core.Models;

namespace TeklaMcp.Server.Tools;

/// <summary>
/// Grid / geometry context tools. They let an agent translate human axis references
/// ("between axes 1 and 2 along axis Д") into model coordinates before creating geometry.
/// </summary>
[McpServerToolType]
public static class ModelGeometryTools
{
    [McpServerTool(Name = "tekla_list_grids")]
    [Description("List grid lines as (axis, label, coordinate in mm). Use to translate axis " +
                 "references like '1', '2', 'Д' into coordinates. NOTE: with the live backend, " +
                 "labels are currently generated by convention (X => 1,2,3; Y => А,Б,В) — verify " +
                 "against the actual model labels.")]
    public static IReadOnlyList<GridLineInfo> ListGrids(ITeklaModelService model)
        => model.GetGrids();

    [McpServerTool(Name = "tekla_resolve_point")]
    [Description("Resolve a model point (X,Y,Z mm) from an X-axis label, a Y-axis label and an " +
                 "elevation, using the model grids. Example: axisX='1', axisY='Д', z=6000.")]
    public static PointResult ResolvePoint(
        ITeklaModelService model,
        [Description("X-axis grid label, e.g. '1'.")] string axisX,
        [Description("Y-axis grid label, e.g. 'Д'.")] string axisY,
        [Description("Elevation Z in mm.")] double z)
        => model.ResolvePoint(axisX, axisY, z);
}
